export interface Employee {
    id?: number; // Assuming this will be auto-generated by the database
    full_name: string;
    date_of_birth: string; // Use string for the date, you can parse it as a Date object if needed
    gender: string;
    contact_number: string;
    email: string;
    address: string;
    aadhar: string;
    isActive: boolean;
  }